name: Staging deployment

on:
  push:
    branches:
      - main

jobs: 
  build:
   
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout files    
        uses: actions/checkout@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: funxtreem/openmct_tutorial
          tag_with_ref: true
          tag_with_sha: true

