name: Staging deployment

on:
  push:
    tags:
    - stage-*

jobs: 
  build:
   
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout files    
        uses: actions/checkout@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: funxtreem/openmct_tutorial
          tag_with_ref: true
          tag_with_sha: true
        
  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout files    
        uses: actions/checkout@v3
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         
      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "openmct_tutorial" --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait


    
